/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDoApp;

import ToDoApp.controller.ProjectController;
import ToDoApp.util.Connectionfactory;
import java.sql.Connection;
import ToDoApp.model.Project;
import ToDoApp.model.Task;
import java.sql.SQLException;
import java.util.List;
import ToDoApp.controller.TaskController;
import java.util.Date;

public class App {

    public static void main(String[] args) throws SQLException {
        Connection c = Connectionfactory.getConnection();

        Connectionfactory.closeConnection(c);

//      ProjectController projectController = new ProjectController();
//      
//      Project project = new Project();
//      project.setName("PROJETO TESTE");
//      project.setDescription("description");
//      projectController.save(project);
//      
//        ProjectController projectController = new ProjectController();
//
//        Project project = new Project();
//        project.setId(3);
//        project.setName("novo nome");
//        project.setDescription("description");
//        projectController.update(project);
//
//        projectController.removeByID(5);

//        List<Project> projects = projectController.getAll();
//        System.err.println("TOTAL DE PROJETOS" + projects.size());

        TaskController taskController = new TaskController();
//        Task task = new Task();
//        task.setIdProject(1);
//        task.setName("Criar as telas de aplicação");
//        task.setDescription("Devem ser criadas as telas para cadastro");
//        task.setNotes("Sem notas");
//        task.setCompleted(false);
//        task.setDeadline(new Date());
//        
//        taskController.save(task);


        
//        Task task = new Task();
//        task.setIdProject(1);
//        task.setId(11);
//        
//        task.setDescription("Devem ser criadas as telas da aplicação");
//        task.setName("Criar telas da aplicação");
//        task.setNotes("Sem notas");
//        task.setCompleted(false);
//        task.setDeadline(new Date());
//        taskController.update(task);


            taskController.removeByID(11);
        
        

    }

    Object getGreeting() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
