/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ToDoApp.view;

import ToDoApp.controller.ProjectController;
import ToDoApp.model.Project;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class ProjectDialogScreen extends javax.swing.JDialog {

    ProjectController controller;

    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        controller = new ProjectController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTollBarProjectsDialogScreen = new javax.swing.JPanel();
        jLabelAddProjectsDialogSCreen = new javax.swing.JLabel();
        jLabelTitleProjectsDialogScreen = new javax.swing.JLabel();
        jPanelMainProjectsDialogScreen = new javax.swing.JPanel();
        jLabelNameProjectsDialogScreen = new javax.swing.JLabel();
        jTextFieldNameProjectsDialogScreen = new javax.swing.JTextField();
        jLabelDescriptionDialogScreen = new javax.swing.JLabel();
        jScrollPaneDescriptionProjectsDialogScreen = new javax.swing.JScrollPane();
        jTextAreaDescriptionProjectsDialogScreen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        jPanelTollBarProjectsDialogScreen.setBackground(new java.awt.Color(53, 59, 80));
        jPanelTollBarProjectsDialogScreen.setPreferredSize(new java.awt.Dimension(400, 70));

        jLabelAddProjectsDialogSCreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAddProjectsDialogSCreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-selecionado-35.png"))); // NOI18N
        jLabelAddProjectsDialogSCreen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelAddProjectsDialogSCreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAddProjectsDialogSCreenMouseClicked(evt);
            }
        });

        jLabelTitleProjectsDialogScreen.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabelTitleProjectsDialogScreen.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitleProjectsDialogScreen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitleProjectsDialogScreen.setText("Projeto");

        javax.swing.GroupLayout jPanelTollBarProjectsDialogScreenLayout = new javax.swing.GroupLayout(jPanelTollBarProjectsDialogScreen);
        jPanelTollBarProjectsDialogScreen.setLayout(jPanelTollBarProjectsDialogScreenLayout);
        jPanelTollBarProjectsDialogScreenLayout.setHorizontalGroup(
            jPanelTollBarProjectsDialogScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTollBarProjectsDialogScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleProjectsDialogScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAddProjectsDialogSCreen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTollBarProjectsDialogScreenLayout.setVerticalGroup(
            jPanelTollBarProjectsDialogScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTollBarProjectsDialogScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTollBarProjectsDialogScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddProjectsDialogSCreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTollBarProjectsDialogScreenLayout.createSequentialGroup()
                        .addComponent(jLabelTitleProjectsDialogScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanelMainProjectsDialogScreen.setBackground(java.awt.Color.white);

        jLabelNameProjectsDialogScreen.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabelNameProjectsDialogScreen.setText("Nome");

        jTextFieldNameProjectsDialogScreen.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jTextFieldNameProjectsDialogScreen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldNameProjectsDialogScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameProjectsDialogScreenActionPerformed(evt);
            }
        });

        jLabelDescriptionDialogScreen.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jLabelDescriptionDialogScreen.setText("Descrição");

        jTextAreaDescriptionProjectsDialogScreen.setColumns(20);
        jTextAreaDescriptionProjectsDialogScreen.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        jTextAreaDescriptionProjectsDialogScreen.setRows(5);
        jTextAreaDescriptionProjectsDialogScreen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPaneDescriptionProjectsDialogScreen.setViewportView(jTextAreaDescriptionProjectsDialogScreen);

        javax.swing.GroupLayout jPanelMainProjectsDialogScreenLayout = new javax.swing.GroupLayout(jPanelMainProjectsDialogScreen);
        jPanelMainProjectsDialogScreen.setLayout(jPanelMainProjectsDialogScreenLayout);
        jPanelMainProjectsDialogScreenLayout.setHorizontalGroup(
            jPanelMainProjectsDialogScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainProjectsDialogScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainProjectsDialogScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneDescriptionProjectsDialogScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(jTextFieldNameProjectsDialogScreen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNameProjectsDialogScreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescriptionDialogScreen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMainProjectsDialogScreenLayout.setVerticalGroup(
            jPanelMainProjectsDialogScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainProjectsDialogScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNameProjectsDialogScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNameProjectsDialogScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDescriptionDialogScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDescriptionProjectsDialogScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTollBarProjectsDialogScreen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMainProjectsDialogScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTollBarProjectsDialogScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanelMainProjectsDialogScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameProjectsDialogScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameProjectsDialogScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameProjectsDialogScreenActionPerformed

    private void jLabelAddProjectsDialogSCreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAddProjectsDialogSCreenMouseClicked
        // TODO add your handling code here:
        try {
            if(!jTextFieldNameProjectsDialogScreen.getText().equals("")){
                Project project = new Project();
                project.setName(jTextFieldNameProjectsDialogScreen.getText());
                project.setDescription(jTextAreaDescriptionProjectsDialogScreen.getText());

                controller.save(project);
                JOptionPane.showMessageDialog(rootPane, "Projeto salvo com sucesso");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "O projeto não foi salvo "
                        + "pois o campo nome não foi preenchido");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

        
    }//GEN-LAST:event_jLabelAddProjectsDialogSCreenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAddProjectsDialogSCreen;
    private javax.swing.JLabel jLabelDescriptionDialogScreen;
    private javax.swing.JLabel jLabelNameProjectsDialogScreen;
    private javax.swing.JLabel jLabelTitleProjectsDialogScreen;
    private javax.swing.JPanel jPanelMainProjectsDialogScreen;
    private javax.swing.JPanel jPanelTollBarProjectsDialogScreen;
    private javax.swing.JScrollPane jScrollPaneDescriptionProjectsDialogScreen;
    private javax.swing.JTextArea jTextAreaDescriptionProjectsDialogScreen;
    private javax.swing.JTextField jTextFieldNameProjectsDialogScreen;
    // End of variables declaration//GEN-END:variables
}
